# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e44ddf4a7c5736b71f84d837748720d90ab6b0b52fb2bf2d4d8e0d44e1a079ed2c1ec407fe7448ad2d369ff04f202dbf1b8bf1961f2810e0e90734298d57861c

test:
  secret_key_base: 4ee4aab261bc59fb5ea63748f19813fa2ffe85e11a24d93f1ba55f056fd2071711f369ecb14a408d977c897ca008000c26facd8c92a037af05dd633c2b93451a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
